// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pciwvlciwitsimsofslw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjaXd2bGNpd2l0c2ltc29mc2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTY2NzQsImV4cCI6MjA3MTM5MjY3NH0.PKO3CcYsiTF1WPxXsdfUg9RC6EfdDbnO2ZcL_jSiPZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});